"""added foreign key mapping

Revision ID: 023ac2b0c826
Revises: ceb9488bf40e
Create Date: 2024-09-11 07:05:24.976020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '023ac2b0c826'
down_revision: Union[str, None] = 'ceb9488bf40e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'post_comments', 'prompts', ['prompt_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'post_likes', 'prompts', ['prompt_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post_likes', type_='foreignkey')
    op.drop_constraint(None, 'post_comments', type_='foreignkey')
    # ### end Alembic commands ###
