"""upgrade model

Revision ID: 195f79c24ff3
Revises: 9f0c709a6cf8
Create Date: 2024-11-07 16:46:07.689431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '195f79c24ff3'
down_revision: Union[str, None] = '9f0c709a6cf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prompts', sa.Column('chain', sa.String(), nullable=True))
    op.add_column('prompts', sa.Column('ai_model', sa.String(), nullable=True))
    op.add_column('prompts', sa.Column('grant_access', sa.Boolean(), nullable=True, default=False))
    op.create_index(op.f('ix_prompts_ai_model'), 'prompts', ['ai_model'], unique=False)
    op.create_index(op.f('ix_prompts_chain'), 'prompts', ['chain'], unique=False)
    op.create_index(op.f('ix_prompts_grant_access'), 'prompts', ['grant_access'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prompts_grant_access'), table_name='prompts')
    op.drop_index(op.f('ix_prompts_chain'), table_name='prompts')
    op.drop_index(op.f('ix_prompts_ai_model'), table_name='prompts')
    op.drop_column('prompts', 'grant_access')
    op.drop_column('prompts', 'ai_model')
    op.drop_column('prompts', 'chain')
    # ### end Alembic commands ###
