"""added cid for premium prompts

Revision ID: 8cc632fd8e50
Revises: 4bae3c93c3be
Create Date: 2024-09-13 16:09:50.452406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8cc632fd8e50'
down_revision: Union[str, None] = '4bae3c93c3be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prompts', sa.Column('cid', sa.String(), nullable=True))
    op.create_index(op.f('ix_prompts_cid'), 'prompts', ['cid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prompts_cid'), table_name='prompts')
    op.drop_column('prompts', 'cid')
    # ### end Alembic commands ###
