"""Added video url

Revision ID: 9f0c709a6cf8
Revises: fb19deaccd3e
Create Date: 2024-10-02 23:13:59.910047

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9f0c709a6cf8'
down_revision: Union[str, None] = 'fb19deaccd3e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prompts', sa.Column('video_url', sa.String(), nullable=True))
    op.create_index(op.f('ix_prompts_video_url'), 'prompts', ['video_url'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prompts_video_url'), table_name='prompts')
    op.drop_column('prompts', 'video_url')
    # ### end Alembic commands ###
