"""added encryption

Revision ID: ce3ca30a6baa
Revises: e5b0292f533a
Create Date: 2024-09-12 18:49:36.227100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce3ca30a6baa'
down_revision: Union[str, None] = 'e5b0292f533a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('encrypted_keys',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_key', sa.String(), nullable=False),
    sa.Column('encrypted_private_key', sa.String(), nullable=False),
    sa.Column('unique_keyword_hash', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_encrypted_keys_id'), 'encrypted_keys', ['id'], unique=False)
    op.drop_index('ix_encrypt_items_description', table_name='encrypt_items')
    op.drop_index('ix_encrypt_items_id', table_name='encrypt_items')
    op.drop_index('ix_encrypt_items_title', table_name='encrypt_items')
    op.drop_table('encrypt_items')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('encrypt_items',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='encrypt_items_pkey')
    )
    op.create_index('ix_encrypt_items_title', 'encrypt_items', ['title'], unique=False)
    op.create_index('ix_encrypt_items_id', 'encrypt_items', ['id'], unique=False)
    op.create_index('ix_encrypt_items_description', 'encrypt_items', ['description'], unique=False)
    op.drop_index(op.f('ix_encrypted_keys_id'), table_name='encrypted_keys')
    op.drop_table('encrypted_keys')
    # ### end Alembic commands ###
