"""updated model relationships between prompts and comments and likes

Revision ID: ceb9488bf40e
Revises: 3f06534fe231
Create Date: 2024-09-11 07:02:44.146552

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ceb9488bf40e'
down_revision: Union[str, None] = '3f06534fe231'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
