"""added encryption

Revision ID: e5b0292f533a
Revises: 023ac2b0c826
Create Date: 2024-09-12 18:44:25.518961

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5b0292f533a'
down_revision: Union[str, None] = '023ac2b0c826'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('encrypt_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_encrypt_items_description'), 'encrypt_items', ['description'], unique=False)
    op.create_index(op.f('ix_encrypt_items_id'), 'encrypt_items', ['id'], unique=False)
    op.create_index(op.f('ix_encrypt_items_title'), 'encrypt_items', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_encrypt_items_title'), table_name='encrypt_items')
    op.drop_index(op.f('ix_encrypt_items_id'), table_name='encrypt_items')
    op.drop_index(op.f('ix_encrypt_items_description'), table_name='encrypt_items')
    op.drop_table('encrypt_items')
    # ### end Alembic commands ###
